name: Bug Report
description: "Report something that's broken."
body:
  - type: input
    attributes:
      label: Package Version
      description: Provide the package version that you are using. [Please ensure it is still supported.](https://github.com/domainvalidity/php-domain-validator?tab=security-ov-file#supported-versions)
      placeholder: 2.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue. If necessary, please provide a GitHub repository to demonstrate your issue
    validations:
      required: true
